apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      initContainers:
      - name: set-config-ownership
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          runAsUser: 0 # Run as root to be able to chown
      containers:
      - name: jellyfin
        image: ghcr.io/hotio/jellyfin:latest
        ports:
        - containerPort: 8096
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: TZ
        volumeMounts:
        - name: config
          mountPath: /config
          # No subPath needed as this volume is dedicated
        - name: cache
          mountPath: /cache
          subPath: jellyfin/cache
        - name: media
          mountPath: /data/usenet/media
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups:
        - 107  # render group
        - 44   # video group
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc # Use the new PVC
      - name: cache
        persistentVolumeClaim:
          claimName: appdata-pvc # Keep appdata-pvc for cache
      - name: media
        persistentVolumeClaim:
          claimName: media-storage-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
