# NodePort services for development - expose services directly
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 7878
    targetPort: 7878
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 8989
    targetPort: 8989
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 6767
    targetPort: 6767
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
    name: web
  - port: 9090
    targetPort: 9090
    nodePort: 30005
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 9696
    targetPort: 9696
    nodePort: 30006
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 8097
    targetPort: 8096
    nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: media-server-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30009
    name: https
