apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-server

resources:
  - common
  - radarr
  - sonarr
  - bazarr
  # Uncomment as needed:
  # - sabnzbd
  # - prowlarr
  # - jellyfin
  # - heimdall
  # - ytplaylistarr

commonLabels:
  app.kubernetes.io/part-of: arr-stack
  app.kubernetes.io/managed-by: kustomize
