apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-server

resources:
  - ../../base

patches:
  - path: patch-ingress.yaml
  - path: patch-resources.yaml

commonLabels:
  environment: production
