apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: ghcr.io/hotio/bazarr:latest
        ports:
        - containerPort: 6767
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: PGID
        - name: UMASK
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: UMASK
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: TZ
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: bazarr
        - name: downloads
          mountPath: /data/usenet/downloads
        - name: media
          mountPath: /data/usenet/media
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: appdata-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: usenet-downloads-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-storage-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media-server
spec:
  selector:
    app: bazarr
  ports:
  - protocol: TCP
    port: 6767
    targetPort: 6767
  type: ClusterIP
