apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: arr-stack-config
              key: TZ
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: heimdall
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: appdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: media-server
spec:
  selector:
    app: heimdall
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  type: ClusterIP
